### PR TITLE
Add support for Ubuntu 16.04's php 7.0 packages

### PR DESCRIPTION
**Pull request by andytson-inviqa**
Note, the service provider changed to systemd in 15.04, and the latest version of chef knows 13.10 uses upstart, however I'm keeping the original code for the service provider in, so this can be part of a BC release.

### CODE REVIEW

**Comment by irvingpop** [comment]
👍  this branch solved my issue on Ubuntu 16.04

**Comment by guywithnose** [comment]
:+1:

**Comment by chrisryan** [comment]
:+1: Also solves an issue I was encountering with Ubuntu 16.04. I could fork but would _really_ not want to do that.

**Comment by krishnaramya** [comment]
:+1:

**Comment by boweevil** [comment]
👍

**Comment by yevgenko** [comment]
Thank you for PR and sorry about taking long on this!

**Pull request merged**
