### PR TITLE
Allow install op php5.6 on centos6.6 en 7.x

### PR DESCRIPTION
**Pull request by daften**

### CODE REVIEW

**Comment by glensc** [comment]
looks too complex, shouldn't you use yum cookbook to setup repos instead?

**Comment by daften** [comment]
I couldn't find the repository itself anywhere to add it like that.

**Comment by glensc** [comment]
err, look at your own changes:

```diff
+          rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
+          creates '/etc/yum.repos.d/webtatic.repo'
```

look inside `/etc/yum.repos.d/webtatic.repo` -- that's the repo definition!

**Comment by daften** [comment]
There are actually 3 repo definitions installed through the rpm, which one delivers which packages i don't know. Is the hash also in the installed definition?

**Comment by daften** [comment]
No longer needed, switched to remi repo's myself.

**Comment by yevgenko** [comment]
thanks for updating

**Pull request closed without merging**
