### PR TITLE
The ability to chose to install or upgrade package and which version it should be.

### PR DESCRIPTION
**Pull request by Kasen**
This PR adds the ability to chose to install or upgrade package and which version it should be.
I made this PR, because upgrading of php packages on each chef-client run is not good idea. It led to the fact that part of our functionality stopped work. PR doesn't break backward compatibility.

### CODE REVIEW

**Comment by Kasen** [comment]
@yevgenko review, please. This is very important for us.

**Comment by yevgenko** [comment]
Hey @Kasen, thank you very much for PR and sorry for delays with review, I'll try to do it ASAP :)

**Comment by yevgenko** [comment]
I'm on it :)

**Comment by yevgenko** [comment]
meanwhile there is one more PR #67, suggesting to use install action by default, which seems reasonable to me, what do you think?

**Pull request merged**
