### PR TITLE
Add support for Ubuntu 18.04.

### PR DESCRIPTION
**Pull request by leegarrett**

### CODE REVIEW

**Comment by leegarrett** [comment]
Closing and reopening to trigger a rebuild. travis-ci seems to fail on installing chef, so it's unrelated to my PR.

**Comment by leegarrett** [comment]
@yevgenko Can you merge or comment on this? It's fairly trivial, and adds support for the upcoming Ubuntu 18.04.

**Comment by yevgenko** [comment]
thank you @leegarrett 👍

**Comment by leegarrett** [comment]
@yevgenko, you're welcome! Is there any ETA when there's a new release? I don't mind the issue as I use a checkout of the cookbook, but it would be great if others could benefit from this (and many other) fixes since the release last year.

**Pull request merged**
