### PR TITLE
move defaults out of template

### PR DESCRIPTION
**Pull request by glensc**
define them as cookbook attributes

benefits:
- business logic is out of template
- attribute defaults can be overriden per role/environment

replaces: #30

### CODE REVIEW

**Comment by glensc** [comment]
please merge, i have bunch of other changes planned on top of this commit

**Comment by legal90** [comment]
+1 on this. It is really inexplicit to get default values rendered from the template logic. In Chef it's a common practice to use attribute files for that.

**Comment by glensc** [comment]
@yevgenko this cookbook is probably dead? i've trying to push this in since Dec 12, 2013 (#30)

**Comment by yevgenko** [comment]
Hey @glensc, sorry for late response and for ignoring project for awhile, I'll try to catch up with this.

**Pull request merged**
