### PR TITLE
Update method access for node attributes for chef 13

### PR DESCRIPTION
**Pull request by tophercullen**
node.foo.bar is deprecated and will be removed  in chef 13

Signed-off-by: Topher Cullen <topher.cullen@jamberry.com>

### CODE REVIEW

**Comment by axos88** [comment]
+1

**Comment by tophercullen** [comment]
@yevgenko can we get this merged? It looks like this issue has already generated another duplicate PR.

**Comment by sleenen** [comment]
Merge please?

**Comment by yevgenko** [comment]
thank you for PR and sorry for delays, I'll take care of it on this week

**Comment by yevgenko** [comment]
thanks again, new version has been released!

**Pull request merged**
